### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by cfsghost** [svalaskevicius/qtjs-generator#8]
I an trying to build it qtjs-generator with Qt 5.1 on Debian Sid. then I get error when it is parsing xml.

$ ./metagen.sh
...
Parsing /home/fred/sources/qtjs-generator/metagen/xml/class_q_painter_path_1_1_element.xml
Parsing /home/fred/sources/qtjs-generator/metagen/xml/class_q_qml_j_s_1_1_a_s_t_1_1_element_list.xml
Parsing /home/fred/sources/qtjs-generator/metagen/xml/struct_q_qml_list_model_1_1_element_sync.xml
Parsing /home/fred/sources/qtjs-generator/metagen/xml/struct_list_model_1_1_element_sync.xml
Parsing /home/fred/sources/qtjs-generator/metagen/xml/class_q_qml_j_s_1_1_a_s_t_1_1_elision.xml
Parsing /home/fred/sources/qtjs-generator/metagen/xml/class_q_qml_j_s_1_1_a_s_t_1_1_empty_statement.xml
Parsing /home/fred/sources/qtjs-generator/metagen/xml/class_q_qml_j_s_1_1_engine.xml
Parsing /home/fred/sources/qtjs-generator/metagen/xml/struct_q_font_cache_1_1_engine.xml
Parsing /home/fred/sources/qtjs-generator/metagen/xml/class_q_window_system_interface_private_1_1_enter_event.xml
Parsing /home/fred/sources/qtjs-generator/metagen/xml/struct_q_xml_stream_reader_private_1_1_entity.xml
Exception in thread "main" java.lang.NumberFormatException: For input string: "value(str)"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at org.cpgf.metagen.doxyxmlparser.DoxygenXmlParser.doParseField(DoxygenXmlParser.java:427)
        at org.cpgf.metagen.doxyxmlparser.DoxygenXmlParser.doParseSectionDef(DoxygenXmlParser.java:288)
        at org.cpgf.metagen.doxyxmlparser.DoxygenXmlParser.doParseAllSectionDef(DoxygenXmlParser.java:273)
        at org.cpgf.metagen.doxyxmlparser.DoxygenXmlParser.doParseClass(DoxygenXmlParser.java:227)
        at org.cpgf.metagen.doxyxmlparser.DoxygenXmlParser.doParseCompounddef(DoxygenXmlParser.java:208)
        at org.cpgf.metagen.doxyxmlparser.DoxygenXmlParser.doParaseXmlDocument(DoxygenXmlParser.java:179)
        at org.cpgf.metagen.doxyxmlparser.DoxygenXmlParser.parseFile(DoxygenXmlParser.java:85)
        at org.cpgf.metagen.doxyxmlparser.DoxygenXmlParser.doParseCompound(DoxygenXmlParser.java:192)
        at org.cpgf.metagen.doxyxmlparser.DoxygenXmlParser.doParaseXmlDocument(DoxygenXmlParser.java:176)
        at org.cpgf.metagen.doxyxmlparser.DoxygenXmlParser.parseFile(DoxygenXmlParser.java:85)
        at org.cpgf.metagen.MetagenMain.run(MetagenMain.java:100)
        at metagen.main(metagen.java:25)

**Comment by svalaskevicius** [comment]
Hi @cfsghost,

Only Qt 5.2 and up are supported at this time - this is because they've removed the embedded V8 from Qt in 5.2, and this allows linking an external library. Sadly, when I made the switch to the Node's V8 I haven't updated the README - sorry for that - it is now fixed.

Please can you try using Qt 5.2?

Also, please update the source again as I've built qtjs generator on debian sid and fixed the issue with the newer doxygen - it was misunderstanding class constructor initialisers as properties of that class (the current fix is to remove all initialisers while preprocessing the headers for doxygen).

Please let me know if have any more issues - although as I've just built it on debian sid VM, I noticed there are some segfaults I've never seen - this may be because the g++ 4.8 or different system libraries.. will debug them once I have some more time (on Linux Mint 15 Olivia its quite stable).

Thanks!

**Comment by svalaskevicius** [comment]
An update regarding the segfaults - I've fixed the one in feature tests, however there is still another when using in virtualbox VM - Mesa's renderer (Gallium) is using LLVM which conflicts with the LLVM linked with the application - this only causes problems in the QML example and widgets.js example is working ok. 

Chances are, that'll work in your environment, given you're using HW based OpenGL implementation (w/o LLVM).

Another thing to keep in mind, that QML example (as its using QtQuick 2) requires OpenGL 2.0 or newer.

**Comment by svalaskevicius** [comment]
update - to reduce the build requirements, I've committed the generated build files so the doxygen step is only required to build with Qt other than 5.2.

I'm closing this ticket as the original issue with doxygen versions was fixed
